### ISSUE TITLE
Wrong url on outdated sourceforge location

### ISSUE THREAD

**Issue by slavianp** [exzombie/prll#6]
The project has been hosted on sourceforge:
http://prll.sourceforge.net/. 
It is still the first hit returned by Google search.
The home page on sourceforge says the project is relocated to:
http://gitorious.org/prll
This url returns 404. It took me  a while to find the current project location.

**Comment by exzombie** [comment]
Thanks, fixed! I can't believe I didn't notice this issue for so long :roll_eyes:
